name: Pylint

on: [push]

env:
  PYTHON_VER: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "$PYTHON_VER"
      uses: actions/setup-python@v4
      with:
        python-version: "$PYTHON_VER"
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        python -m pylint -d C0114,C0115,C0116,C0209,C0103,W1514,C0200,R --max-line-length=120 $(git ls-files '*.py')
