name: Pylint

on: [push]

env:
  PY_VER: "3.12"

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest
      uses: actions/checkout@v4
    - name: "Set up Python ${{ env.PY_VER }}"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PY_VER }}
        cache: 'pip'
    - name: Install pylint with pip
      run: pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        python -m pylint -d W1514,C,R --max-line-length=120 $(git ls-files '*.py')
